root = "."
tmp_dir = "tmp"

[build]
  cmd = "go run ./services/gateway"
  bin = ""
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "html", "tpl", "tmpl"]
  kill_delay = "500ms"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true