root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp\\link-checker.exe"
  cmd = "go build -o tmp\\link-checker.exe ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_dir = [".", "core", "handlers"]
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = false

[log]
  time = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"